heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a Cassandra cluster.

parameter_groups:
- label:  Server Settings
  parameters:
  - node_count
  - image
  - flavor

- label: rax-dev-params
  # These are parameters that will not be displayed in the portal. The purpose
  # of these parameters are for users who are developing or testing newer or
  # different setups. If any of these parameters are changed, there is a good
  # chance this stack will fail to properly deploy.
  parameters:
  - seed_hostname
  - node_hostnames
  - kitchen
  - chef_version
  - child_template

parameters:

  # Server settings
  seed_hostname:
    label: Seed Hostname
    description: Cassandra seed node hostname
    type: string
    default: cassandra-seed
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  node_hostnames:
    label: Node Hostnames
    description: Cassandra node hostnames
    type: string
    default: cassandra-node%index%
    constraints:
    - length:
        min: 1
        max: 64

  node_count:
    label: Node Count
    description: Number of Cassandra nodes
    type: number
    default: 2
    constraints:
    - range:
        min: 2
        max: 72
      description: Must have at least two nodes in addition to the seed node.

  image:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: |
      Rackspace Cloud Server flavor to use. The size is based on the amount of
      RAM for the provisioned server.
    type: string
    default: 2 GB General Purpose v1
    constraints:
    - allowed_values:
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/cassandra

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 11.12.8

  child_template:
    label: Child Template
    description: URL to the child template for deploying Cassandra nodes.
    type: string
    default: https://raw.githubusercontent.com/rackspace-orchestration-templates/cassandra/master/cassandra-node.yaml

resources:
  # SSH Key
  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  # Server resources
  seed_node:
    type: "OS::Nova::Server"
    properties:
      name: { get_param: seed_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }

  seed_setup:
    type: "OS::Heat::ChefSolo"
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [seed_node, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        cassandra:
          listen_address: { get_attr: [seed_node, networks, private, 0] }
          broadcast_address: { get_attr: [seed_node, networks, private, 0] }
          rpc_address: { get_attr: [seed_node, networks, private, 0] }
          seeds: { get_attr: [seed_node, networks, private, 0] }
        java:
          jdk_version: 7
        rax:
          firewall:
            tcp: [7000]
          disk_config:
            mount_point: /var/lib/cassandra
        run_list: ["recipe[apt]",
                   "recipe[rax-disk-config]",
                   "recipe[cassandra::datastax]",
                   "recipe[rax-firewall]"]

  nodes:
    type: "OS::Heat::ResourceGroup"
    depends_on: seed_setup
    properties:
      count: { get_param: node_count }
      resource_def:
        type: { get_param: child_template }
        properties:
          stack_id: { get_param: "OS::stack_id" }
          node_hostname: { get_param: node_hostnames }
          image: { get_param: image }
          flavor: { get_param: flavor }
          kitchen: { get_param: kitchen }
          chef_version: { get_param: chef_version }
          seed: { get_attr: [seed_node, networks, private, 0] }
          ssh_keypair_name: { get_resource: ssh_key }
          ssh_private_key: { get_attr: [ssh_key, private_key] }
          ssh_public_key: { get_attr: [ssh_key, public_key] }

outputs:
  private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }

  seed_node_public_ip:
    description: Seed Node IP
    value: { get_attr: [seed_node, accessIPv4] }

  node_public_ips:
    description: Node IPs
    value: { get_attr: [nodes, public_ip] }
